name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn -B verify --file pom.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: apophysis-j-jar
        path: target/apophysis-j-*.jar
        retention-days: 7
